---
- hosts: all
  sudo: true
  vars:
      home: /home/ubuntu
      document_root: /vagrant
  gather_facts: no
  pre_tasks:
    - name: Install Python 2
      raw: sudo apt-get -y install python-simplejson
    - name: Symlink sh to bash rather than dash
      file: src=/bin/bash dest=/bin/sh state=link force=true
    - name: Update apt cache and optionally upgrade
      apt:
        update_cache=yes
        cache_valid_time=7200
        #upgrade=yes # Uncomment this to force full upgrade!
    - name: Install stuff from Aptitude
      apt: name={{ item }} state=installed
      with_items:
       - python-minimal
       - python-pexpect
       - build-essential
       - git
       - tig
       - vim
       - gdb
       - cgdb
       - bash-completion # Not included in the docker image
       - make
       - tree
       - htop
       - tmux
    - name: Set a password that we know
      expect:
        command: passwd ubuntu
        responses:
          (?i)password: "changethis..."
  roles:
      - { role: desktop, sudo: false }
      - { role: dotfiles, sudo: false }
      - { role: python, sudo: false }
      #- { role: jedi-vim, sudo: false }
      - { role: luigi, sudo: false }
      - { role: java, sudo: false }
      - { role: sciluigi_usecase, sudo: false }
