---
- name: Install some required packages from apt
  apt:
      name={{ item }} state=installed
  with_items:
      - mysql-client
      - mysql-server
      - mysql-common
      - libmysqlclient-dev
      - python-mysqldb
  sudo: true
- name: Start the MySQL service
  sudo: yes
  service:
    name: mysql
    state: started
    enabled: true
- name: Update mysql root password for all root accounts
  sudo: yes
  mysql_user:
    name=root
    host={{ item }}
    password={{ mysql_root_password }}
    login_user=root
    login_password={{ mysql_root_password }}
    check_implicit_admin=yes
    priv=*.*:ALL,GRANT
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
    - '%'
- name: Create project folder
  file:
      path={{ home }}/proj
      state=directory
      mode=0755
- name: Create symlink to sciluigi_usecase project folder
  file:
      src=/vagrant/roles/sciluigi_usecase/files/sciluigi_usecase_proj
      dest=/home/ubuntu/proj/sciluigi_usecase
      state=link
