---
- name: Install some required packages from apt
  apt:
      name={{ item }} state=installed
  with_items:
      - mysql-client
      - mysql-server
  sudo: true
- name: Create project folder
  file:
      path={{ home }}/proj
      state=directory
      mode=0755
- name: Create symlink to sciluigi_usecase project folder
  file:
      src=/vagrant/roles/sciluigi_usecase/files/sciluigi_usecase_proj
      dest=/home/ubuntu/proj/sciluigi_usecase
      state=link
